[env]
# RUSTC_WRAPPER = "sccache"
RUST_WITHOUT = "rust-docs"
# ASDF_RUST_PROFILE = "minimal"
MISE_CARGO_BINSTALL = "true"

[tools]
"aqua:cargo-bins/cargo-binstall" = "1"
rust = "1.80"
make = "latest"
# # experimental
"cargo:cargo-nextest" = "0.9"
# "cargo:cargo-hack" = "latest"
"cargo:cargo-deny" = "0.16"
# "cargo:git-cliff" = "latest"
"cargo:dprint" = "0.45"
