---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

pull-requests: write

jobs:
  release-plz:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # we use Release-plz-token (personal token) to explicitly specify github-actions
          # that it is the user who is running the action.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
