name: test

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Git commit sha, on which, to run this workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Run - test_${{ matrix.test_projects }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_projects:
          - cargo_nextest
          - cargo_check
          - cargo_machete
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - uses: actions/cache@v4
        continue-on-error: false
        with:
            path: |
              ~/.cargo/bin
              ~/.cargo/registry
              ~/.cargo/git/db/
            key: ${{ runner.os }}-sdk-rust-${{ hashFiles('**/Cargo.lock') }}
            restore-keys: |
                 ${{ runner.os }}-sdk-rust-
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest,cargo-deny, cargo-hack, cargo-machete
      - name: Run test ${{ matrix.test_projects }}
        run:  make -f Makefile test_${{ matrix.test_projects }}
